// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkL0IGKd-MwhsaBQumFeDjkKqiLuKuV2s',
    appId: '1:736448350309:web:b9eb92a440c233bdf41e8c',
    messagingSenderId: '736448350309',
    projectId: 'pad-c6697',
    authDomain: 'pad-c6697.firebaseapp.com',
    storageBucket: 'pad-c6697.firebasestorage.app',
    measurementId: 'G-DMVX5S8KPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvgroNlgdLqh7G8i0IBE4TIzkI5uc4qA',
    appId: '1:736448350309:android:92c4c5139356c5fdf41e8c',
    messagingSenderId: '736448350309',
    projectId: 'pad-c6697',
    storageBucket: 'pad-c6697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5BuQA0D8wEUXsurO7kH3nIY_-HZji150',
    appId: '1:736448350309:ios:ed5950f7a0a98b52f41e8c',
    messagingSenderId: '736448350309',
    projectId: 'pad-c6697',
    storageBucket: 'pad-c6697.firebasestorage.app',
    iosBundleId: 'com.ksoftm.securepad.securePad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5BuQA0D8wEUXsurO7kH3nIY_-HZji150',
    appId: '1:736448350309:ios:ed5950f7a0a98b52f41e8c',
    messagingSenderId: '736448350309',
    projectId: 'pad-c6697',
    storageBucket: 'pad-c6697.firebasestorage.app',
    iosBundleId: 'com.ksoftm.securepad.securePad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkL0IGKd-MwhsaBQumFeDjkKqiLuKuV2s',
    appId: '1:736448350309:web:2edab508accf78b8f41e8c',
    messagingSenderId: '736448350309',
    projectId: 'pad-c6697',
    authDomain: 'pad-c6697.firebaseapp.com',
    storageBucket: 'pad-c6697.firebasestorage.app',
    measurementId: 'G-DKB46KZVMF',
  );
}
